<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 02: Evaluate the Diabetes Dataset

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: Import the dataset

In [1]:
#Import the required libraries
import pandas as pd
import numpy as np

In [5]:
#Import the diabetes dataset
df  = pd.read_csv("pima-indians-diabetes.csv",header=None)
df

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

#### 2: Analyze the dataset

In [6]:
#View the first five observations of the dataset
df.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

#### 3: Find the features of the dataset

In [7]:
#Use the .NAMES file to view and set the features of the dataset
feature_names = ['Pregnant','Glucose','Diastolic BP','Triceps thickness','serum','BMI','DPF','Age','class']

In [8]:
#Use the feature names set earlier and fix it as the column headers of the dataset
df.columns = feature_names

In [9]:
#Verify if the dataset is updated with the new headers
df.head()

Pregnant  Glucose  Diastolic BP  Triceps thickness  serum   BMI    DPF  \
0         6      148            72                 35      0  33.6  0.627   
1         1       85            66                 29      0  26.6  0.351   
2         8      183            64                  0      0  23.3  0.672   
3         1       89            66                 23     94  28.1  0.167   
4         0      137            40                 35    168  43.1  2.288   

   Age  class  
0   50      1  
1   31      0  
2   32      1  
3   21      0  
4   33      1

In [12]:
#View the number of observations and features of the dataset
print(df.shape)


(768, 9)


#### 4: Find the response  of the dataset

In [17]:
#Select features from the dataset to create the model
feature_cols = ['Pregnant','Glucose','Diastolic BP','Triceps thickness','serum','BMI','DPF','Age']

In [18]:
#Create the feature object
x_features = df[feature_cols]

In [19]:
#Create the reponse object
y_target = df['class']

In [20]:
#View the shape of the feature object
x_features.shape

(768, 8)

In [22]:
#View the shape of the target object
y_target.shape

(768,)

#### 5: Use training and testing datasets to train the model

In [23]:
#Split the dataset to test and train the model
from sklearn import model_selection

x_train,x_test,y_train,y_test = model_selection.train_test_split(x_features,y_target)

#### 6: Create a model  to predict the diabetes outcome

In [29]:
# Create a logistic regression model using the training set
from sklearn.linear_model import LogisticRegression

LogReg = LogisticRegression()

LogReg.fit(x_train,y_train)

C:\Users\HP\AppData\Local\Programs\Python\Python37\Lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [32]:
#Make predictions using the testing set
y_predict = LogReg.predict(x_test)
y_predict

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0], dtype=int64)

#### 7: Check the accuracy of the model

In [33]:
#Evaluate the accuracy of your model
from sklearn import metrics

print(metrics.accuracy_score(y_test,y_predict))

0.7864583333333334


In [36]:
#Print the first 30 actual and predicted responses
print(y_test.values[0:30])

print(y_predict[0:30])

[0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0]
