In [1]:
import numpy as np
import pandas as pd

In [9]:
#load the data set
from sklearn.datasets import load_iris

df =load_iris()

df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
#print the feature of the dataset

print(df['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [18]:
#store data into data frame
df_iris = pd.DataFrame(df.data)

df_iris.columns = df.feature_names

df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [27]:
df.data.shape

(150, 4)

In [28]:
#print dataset target or response shape

df.target.shape

(150,)

In [29]:
#view the target values

df['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
# assign column A with the target values
df_iris['A'] = df.target



In [33]:
df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  A
0                5.1               3.5                1.4               0.2  0
1                4.9               3.0                1.4               0.2  0
2                4.7               3.2                1.3               0.2  0
3                4.6               3.1                1.5               0.2  0
4                5.0               3.6                1.4               0.2  0

In [34]:
# assign features

x_features  = df.data

In [35]:
# assing target or response


y_target =  df.target

In [36]:
# import linear model - the estimator


from sklearn.linear_model import LinearRegression
linereg = LinearRegression()


In [37]:
# fit data into the estimator

linereg.fit(x_features,y_target)

LinearRegression()

In [40]:
#print the intercept

print("Intercept %.2f" %linereg.intercept_)

Intercept 0.19


In [41]:
#print the coefficient

print("Coefficient %d " %len(linereg.coef_))

Coefficient 4 


In [45]:
#train model split the data set into test and train datasets

from sklearn import model_selection

x_train,x_test,y_train,y_test = model_selection.train_test_split(x_features,y_target)



In [46]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(112, 4) (38, 4) (112,) (38,)


In [47]:
#fit the training sets into the model

linereg.fit(x_train,y_train)

LinearRegression()

In [49]:
#Mean square error or regression sum of squares

print("MSE %.2f" %(np.mean((linereg.predict(x_test)-y_test)**2)))

MSE 0.05


In [50]:
# calculate variance


print(" variance %.2f" %(linereg.score(x_test,y_test)))

 variance 0.93


In [ ]:
# logistic regression

In [ ]:
import numpy as np
import pandas as pd

In [52]:
from sklearn.datasets import load_iris

df = load_iris()

type(df)

sklearn.utils.Bunch

In [54]:
df.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [56]:
# first use KNN algorithm (KNN classifier method)
from sklearn.neighbors import KNeighborsClassifier

In [57]:
# instantiate the KNN estimator
knn =KNeighborsClassifier(n_neighbors=1)

knn

KNeighborsClassifier(n_neighbors=1)

In [58]:
knn.fit(x_features,y_target)

KNeighborsClassifier(n_neighbors=1)

In [59]:
# create object with new values for prediction
x_new = [[3,5,4,1],[5,3,4,2]]


In [60]:
#predict the outcome for the new observation using knn classifier
knn.predict(x_new)

array([1, 1])

In [62]:
#use logistic regression estimator

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

In [64]:
logReg.fit(x_features,y_target)

C:\Users\HP\AppData\Local\Programs\Python\Python37\Lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [65]:
#predict the output using logistic regression
logReg.predict(x_new)

array([0, 1])

In [ ]:
#unsupervised learning -clustering-kmeans algorithm

In [ ]:
import numpy as np
import pandas as pd


In [81]:
from sklearn.cluster import KMeans

from sklearn.datasets import make_blobs

 # no.of samples
n_samples = 300 
# random state value to initialize the center
random_state=20 
# defining number of features as 5
x,y = make_blobs(n_samples=n_samples,n_features=5,random_state=None)

predict_y =KMeans(n_clusters=3,random_state=random_state).fit_predict(x)

predict_y


array([2, 0, 2, 1, 2, 2, 1, 0, 1, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 2,
       2, 0, 2, 1, 1, 1, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1,
       2, 1, 0, 2, 1, 0, 2, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2,
       1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2, 0, 2, 2, 1, 2, 1, 2, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 2, 2, 2, 0, 2, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1,
       2, 1, 2, 1, 1, 0, 1, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 0, 2,
       1, 2, 2, 2, 2, 2, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 2, 1, 1, 0, 2, 2, 0, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0,
       0, 2, 1, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 0,
       0, 1, 0, 1, 2, 2, 1, 1, 0, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 2, 2, 0, 1, 2, 1, 1, 0, 0, 2, 0, 1, 2, 1, 1, 2, 1,
       1, 0, 0, 2, 1, 2, 0, 1, 0, 2, 0, 2, 2, 1])

In [94]:
#PCA (Principal component Analysis) -Dimension reduction


import numpy as np
import pandas as pd

from sklearn.decomposition import PCA

from sklearn.datasets import make_blobs

# define sample and random state

n_sample =20

random_state=20


#generate the dataset with 10 features

x,y = make_blobs(n_samples=n_samples,n_features=10,random_state=None)

#define the PCA estimator with no of reduced components

pca = PCA(n_components=3)

#fit the data into the estimator

pca.fit(x)

print(pca.explained_variance_ratio_,end="\n")


#print the first pca components

first_pca = pca.components_[0]

print(first_pca,end="\n")


#transform the fitted data


pca_reduced = pca.transform(x)


print(pca_reduced,end="\n")


print(pca_reduced.shape)

[0.53003545 0.43273173 0.00582657]
[ 0.32414182 -0.1968084   0.12003367 -0.29452281 -0.37265359 -0.10988552
 -0.02119432 -0.16813139 -0.22227741 -0.72524246]
[[ 1.57701200e+01 -4.85244123e+00  7.29640514e-01]
 [-2.15418282e+00  1.30271045e+01 -9.10377300e-02]
 [ 1.21031758e+01 -4.02256468e+00 -2.96153816e+00]
 [-1.22748509e+01 -8.41124597e+00  3.14923287e-01]
 [ 1.37439008e+01 -3.84758818e+00 -2.28039420e+00]
 [-1.88475195e-01  1.42406678e+01 -6.10733068e-01]
 [-2.83417737e+00  1.23828863e+01 -6.22446087e-01]
 [ 1.34458448e+01 -5.58981677e+00 -1.42044336e+00]
 [ 1.49965943e+01 -5.36675688e+00  1.30882317e-01]
 [-4.04340357e+00  1.27565427e+01  1.60172539e-01]
 [-1.04473393e+01 -7.14881860e+00 -3.55793635e-01]
 [-1.23624835e+01 -9.15619653e+00 -4.88885808e-01]
 [ 1.30874745e+01 -4.50067757e+00  1.05058051e+00]
 [ 1.42105447e+01 -5.77948634e+00 -1.38880802e-01]
 [ 1.42849722e+01 -2.78108542e+00  1.51134099e+00]
 [ 1.35762447e+01 -5.04600615e+00  3.61510740e-01]
 [-1.52634752e+00  1.39304

In [ ]:
#pipeline

In [99]:
import numpy as np
import pandas as pd

#import pipeline

from sklearn.pipeline import Pipeline

#import linear estimator

from sklearn.linear_model import LinearRegression

#import PCA estimator

from sklearn.decomposition import PCA



#chain the estimators together

estimator = [('dim_reduction',PCA()),('linear_model',LinearRegression())]

#put the chain of estimators into a pipeline object


pipeobject = Pipeline(estimator)

pipeobject

#view the first step

pipeobject.steps[0]


#view the second step

pipeobject.steps[1]

#view all the steps in the pipeline

pipeobject.steps

[('dim_reduction', PCA()), ('linear_model', LinearRegression())]

In [ ]:
#Model persistance and evaluation

In [100]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris

df = load_iris()

x_features = df.data
y_targets = df.target

#create the new object for prediction

x_new = [[3,5,4,1],[5,3,4,2]]

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

logReg.fit(x_features,y_targets)

C:\Users\HP\AppData\Local\Programs\Python\Python37\Lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [101]:
predict_y = logReg.predict(x_new)

predict_y

array([0, 1])

In [102]:
#import lib for model persistance


import pickle as pkl


#use dumps method to persist the model


persist_model = pkl.dumps(logReg)


persist_model

b'\x80\x03csklearn.linear_model._logistic\nLogisticRegression\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00penaltyq\x03X\x02\x00\x00\x00l2q\x04X\x04\x00\x00\x00dualq\x05\x89X\x03\x00\x00\x00tolq\x06G?\x1a6\xe2\xeb\x1cC-X\x01\x00\x00\x00Cq\x07G?\xf0\x00\x00\x00\x00\x00\x00X\r\x00\x00\x00fit_interceptq\x08\x88X\x11\x00\x00\x00intercept_scalingq\tK\x01X\x0c\x00\x00\x00class_weightq\nNX\x0c\x00\x00\x00random_stateq\x0bNX\x06\x00\x00\x00solverq\x0cX\x05\x00\x00\x00lbfgsq\rX\x08\x00\x00\x00max_iterq\x0eKdX\x0b\x00\x00\x00multi_classq\x0fX\x04\x00\x00\x00autoq\x10X\x07\x00\x00\x00verboseq\x11K\x00X\n\x00\x00\x00warm_startq\x12\x89X\x06\x00\x00\x00n_jobsq\x13NX\x08\x00\x00\x00l1_ratioq\x14NX\x0e\x00\x00\x00n_features_in_q\x15K\x04X\x08\x00\x00\x00classes_q\x16cnumpy.core.multiarray\n_reconstruct\nq\x17cnumpy\nndarray\nq\x18K\x00\x85q\x19C\x01bq\x1a\x87q\x1bRq\x1c(K\x01K\x03\x85q\x1dcnumpy\ndtype\nq\x1eX\x02\x00\x00\x00i4q\x1f\x89\x88\x87q Rq!(K\x03X\x01\x00\x00\x00<q"NNNJ\xff\xff\xff\xffJ\xff\xff\x

In [104]:
#use joblib.dump to persist the model to a file
import joblib

joblib.dump(logReg,'regresfilename.pkl')

['regresfilename.pkl']

In [106]:
#use joblib.load to persist the model to a file

new_estimator=joblib.load('regresfilename.pkl')

new_estimator

LogisticRegression()