In [1]:
l=["Surya","Varun","Kanth"]
for i,j in enumerate(l):
    print(i,j,sep=" ")

0 Surya
1 Varun
2 Kanth


In [2]:
li=dict((i,j) for i,j in enumerate(l))
print(li)

{0: 'Surya', 1: 'Varun', 2: 'Kanth'}


In [3]:
print("Hello world")

Hello world


In [11]:
import numpy as np
dist=[20,30,40,70]
time=[2,6,8,5]
np_dist=np.array(dist)
np_time=np.array(time)
np_speed=np_dist/np_time
np_speed

array([10.,  5.,  5., 14.])

In [12]:
firstarray=np.array([1,2,3,4])
firstarray

array([1, 2, 3, 4])

In [13]:
zeroarray=np.zeros((3,3))
zeroarray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
onearray=np.ones((2,2))
onearray

array([[1., 1.],
       [1., 1.]])

In [17]:
emptyarray=np.empty((2,3))
emptyarray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
linspace=np.linspace(1,10,4)
linspace

array([ 1.,  4.,  7., 10.])

In [31]:
array=np.arange(27).reshape(3,3,3)
np.ndim(array)

3

In [38]:
array=np.arange(12).reshape(3,4)
np.shape(array)
np.size(array)

12

In [40]:
arr=np.arange(9)
arr.dtype

dtype('int32')

In [41]:
np.add(12,32)

44

In [43]:
abs(np.subtract(35,45))

10

In [45]:
nd_cost=np.array([10,15,12,45,75])*150
print(nd_cost)
print(sum(nd_cost))

[ 1500  2250  1800  6750 11250]
23550


In [51]:
#using greater than
vegetable_costs=np.array([15,25,45,33,27])
arr=sorted(vegetable_costs[vegetable_costs>25])
print(arr)
#using not equal to
print(vegetable_costs[vegetable_costs!=25])
#using less than
print(vegetable_costs[vegetable_costs<25])


[27, 33, 45]
[15 45 33 27]
[15]


In [56]:
#using logical operations
weekly_hrs=np.array([35,30,55,45,60])
np.logical_and(weekly_hrs>30,weekly_hrs<50)
np.logical_or(weekly_hrs>30,weekly_hrs<50)
np.logical_not(weekly_hrs>45)

array([ True,  True, False,  True, False])

In [62]:
array=np.arange(15).reshape(3,5)
print(array)
print(array[:, 1:5])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [98]:
array1=np.arange(27).reshape(3,3,3)
print(array1)
print(array1[:,1:3:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 3  4  5]
  [ 6  7  8]]

 [[12 13 14]
  [15 16 17]]

 [[21 22 23]
  [24 25 26]]]


In [68]:
#using shallow copy
l=np.array([1,2,3])
l1=l.view()
l1[2]=4
print(l1)
print(l)

[1 2 4]
[1 2 4]


In [69]:
#using deep copy
l=np.array([1,2,3,4])
l1=l.copy()
l1[3]=5
print(l1)
print(l)

[1 2 3 5]
[1 2 3 4]


In [101]:
#shape manipulation
array=np.arange(15)
arr_flatten=array.ravel()
print(arr_flatten)
array1=np.array([[1,2,3,4],[5,6,7,8]])
print(np.hsplit(array1,2))
print(np.vsplit(array1,2))
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [88]:
#inverse and trace
array=np.array([[1,2],[3,4]])
np.linalg.inv(array)
np.trace(array)

5

In [89]:
arr=np.array([1,2])
np.transpose(arr)

array([1, 2])

In [96]:
#matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a.dot(b))
np.std(a)
np.var(a)
np.mean(a)

[[19 22]
 [43 50]]


2.5

In [102]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
print(a>4)

[[False False False False False]
 [ True  True  True  True  True]]


In [113]:
a=np.arange(12).reshape(3,4)
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [115]:
#using nditer
for i in np.nditer(a,order="C"):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [116]:
#using forton order
for i in np.nditer(a,order="F"):
    print(i,end=" ")

0 4 8 1 5 9 2 6 10 3 7 11 

In [117]:
for i in np.nditer(a,order="F",flags=['external_loop']):
    print(i,end=" ")

[0 4 8] [1 5 9] [ 2  6 10] [ 3  7 11] 

In [118]:
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*i
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [119]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [121]:
#iterating two arrays simultaneously
for i,j in np.nditer([a,b]):
    print(i,j)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [8]:
import pandas as pd
d=pd.read_csv('GDP.csv')
d

Country  Country Code          1990          1991          1992  \
0           Aruba          ABW  24101.109430  25870.755940  26533.343900   
1     Afghanistan          AFG           NaN           NaN           NaN   
2          Angola          AGO   3089.683369   3120.356148   2908.160798   
3         Albania          ALB   2549.473022   1909.114038   1823.307673   
4      Arab World          ARB   6808.206995   6872.273195   7255.328362   
..            ...          ...           ...           ...           ...   
255        Kosovo          XKX           NaN           NaN           NaN   
256   Yemen, Rep.          YEM   2223.028771   2325.263661   2443.920401   
257  South Africa          ZAF   6424.502215   6414.057923   6261.716184   
258        Zambia          ZMB   1517.926292   1528.781247   1499.340446   
259      Zimbabwe          ZWE   1829.677575   1949.732966   1777.843425   

             1993          1994          1995          1996          1997  \
0    27430.752400  28656.520210  28648.990020  28499.089430  30215.949230   
1             NaN           NaN           NaN           NaN           NaN   
2     2190.768160   2195.532289   2496.199493   2794.896906   2953.342709   
3     2057.449657   2289.873135   2665.764906   2980.066288   2717.362124   
4     7458.647059   7645.682856   7774.207360   8094.149842   8397.515692   
..            ...           ...           ...           ...           ...   
255           NaN           NaN           NaN           NaN           NaN   
256   2472.188808   2569.648739   2657.813447   2730.145147   2829.866193   
257   6331.777580   6520.866604   6719.583315   7000.801619   7179.806651   
258   1600.347799   1457.627696   1493.123972   1572.973238   1616.492883   
259   1807.225700   1986.028160   2004.362417   2227.060619   2303.829588   

     ...          2010          2011          2012          2013  \
0    ...  33732.847450  35492.618490  35498.982090  37419.892820   
1    ...   1637.377987   1626.764793   1806.763930   1874.765634   
2    ...   6230.297028   6346.395122   6772.528333   6980.423038   
3    ...   9628.025783  10207.752350  10526.235450  10571.010650   
4    ...  14127.778020  14518.827450  15423.465390  15824.780110   
..   ...           ...           ...           ...           ...   
255  ...   7782.875107   8222.285712   8547.652384   8903.763429   
256  ...   4472.726448   3876.302619   3935.167105   4084.882967   
257  ...  11728.160490  12179.174190  12488.215570  12815.727070   
258  ...   3269.794329   3419.010460   3634.780353   3765.584162   
259  ...   1888.566739   2168.110293   2534.541919   2583.985638   

             2014          2015          2016          2017          2018  \
0    38223.372260  38249.054870  38390.271650  39454.629830           NaN   
1     1897.525938   1886.692977   1896.992520   1934.636754   1955.006208   
2     7199.245478   7096.600615   6756.935074   6650.584940   6452.355165   
3    11259.225890  11662.030480  11868.178970  12930.140030  13364.155400   
4    16153.244860  16501.792590  16935.383300  17099.889390  17570.137600   
..            ...           ...           ...           ...           ...   
255   9194.741819   9781.019679  10208.857900  10756.663460  11348.363450   
256   4045.500031   3320.110156   2827.691023   2645.308383   2575.126385   
257  13090.476830  13185.253280  13188.029620  13438.282890  13686.882360   
258   3893.549478   3927.761816   3998.004435   4090.120040   4223.906936   
259   2648.568967   2679.580317   2687.385429   2825.725122   3029.793005   

     2019  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
..    ...  
255   NaN  
256   NaN  
257   NaN  
258   NaN  
259   NaN  

[260 rows x 32 columns]